# Compiler and Flags
COMP=g++
FLAGS=-Wall -std=c++11

output: social_network.o network.o user.o
    g++ social_network.o network.o user.o -o output

social_network.o social_network.cpp network.h user.h
    g++ -c social_network.cpp -o social_network.o

network.o: network.cpp network.h user.h
    g++ -c network.cpp -o network.o

user.o: user.cpp user.h
    g++ -c user.cpp -o user.o

clean:
    rm *.o output